apiVersion: v1
kind: Pod
metadata:
  name: go-benchmarker
spec:
  containers:
    - name: go-benchmarker
      image: ricogustavo/go-benchmarker:latest
      args: ["--cpu", "1", "--memory", "512", "--disk", "1000"]
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 1Gi
